name: librarian_frontend
description: This project contains the frontend application for the Librarian platform.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  cached_network_image: ^3.2.3
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_jailbreak_detection: ^1.8.0
  flutter_native_splash: ^2.2.16
  flutter_rating_bar: ^4.0.1
  flutter_redux: ^0.10.0
  flutter_speed_dial: ^6.2.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^5.4.2
  http: ^0.13.5
  in_app_purchase: ^3.0.8
  introduction_screen: ^3.1.1
  provider: ^6.0.5
  redux: ^5.0.0
  shared_preferences: ^2.0.15
  toggle_switch: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: CarroisSC
      fonts:
        - asset: assets/fonts/CarroisGothicSC-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: AlegreyaSC
      fonts:
        - asset: assets/fonts/AlegreyaSansSC-Regular.ttf
        - asset: assets/fonts/AlegreyaSansSC-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSansSC-Bold.ttf
          weight: 700