final Map<String, dynamic> englishStrings = <String, dynamic>{
  'app-title': 'Librarian',
  'login-button': 'Login',
  'register-button': 'Register',
  'cancel': 'Cancel',
  'search': 'Search',
  'yes': 'Yes',
  'no': 'No',
  'exit-confirmation-message': 'Do you want to exit?',
  'google-sign-in-button': 'Sign in with Google',
  'search-collection': 'Search collection ...',
  'languages-en': 'English',
  'languages-fr': 'French',
  'languages-es': 'Spanish',
  //
  'login.email': 'Email',
  'login.password': 'Password',
  'login.sign-in': 'Sign In',
  'login.verify-email': 'Verify email address before signing in!',
  'login.error-initializing': 'Error initializing Firebase',
  'login.empty-email': 'Email cannot be empty!',
  'login.email-format': 'Email must be proper format!',
  'login.empty-password': 'Password cannot be empty!',
  'login.create-account': 'Sign Up',
  'login.forgot-password': 'Forgot Password?',
  //
  'drawer.1-book-msg': '1 book in library',
  'drawer.no-books-msg': 'No books in library',
  'drawer.num-books-msg': '{} books in library',
  'drawer.signed-in-as': 'Signed in as',
  'drawer.about-app': 'About app',
  'drawer.sign-out': 'Sign out',
  'drawer.settings.title': 'Settings',
  'drawer.settings.dark-mode': 'Dark Mode',
  'drawer.settings.light-mode': 'Light Mode',
  //
  'parse-error.author': 'Unknown author',
  'parse-error.title': 'Unknown title',
  'parse-error.publisher': 'Unknown Publisher',
  //
  'manual-search-dialog.title': 'Keyword Search',
  'manual-search-dialog.body':
      'Search for new books using one or more keywords below',
  'manual-search-dialog.search-row-labels.keywords': 'Keywords',
  'manual-search-dialog.search-row-labels.title': 'Title',
  'manual-search-dialog.search-row-labels.author': 'Author',
  'manual-search-dialog.search-row-labels.publisher': 'Publisher',
  'manual-search-dialog.search-row-labels.isbn': 'ISBN',
  //
  'book-details-screen.page-count': '{} pages',
  'book-details-screen.publisher': 'Published {} by {}',
  'book-details-screen.in-faves': 'In Faves',
  'book-details-screen.in-wishlist': 'In Wishlist',
  'book-details-screen.in-shopping-list': 'In Shopping List',
  'book-details-screen.have-read': 'Have Read',
  //
  'fancy-fab.barcode-search': 'Search by barcode',
  'fancy-fab.keyword-search': 'Search by keywords',
  'fancy-fab.add-book-manually': 'Add book manually',
  //
  'filter-bar.new': 'New',
  'filter-bar.old': 'Old',
  'filter-bar.author-asc': 'Author Asc',
  'filter-bar.author-desc': 'Author Desc',
  'filter-bar.title-asc': 'Title Asc',
  'filter-bar.title-desc': 'Title Desc',
  'filter-bar.published-asc': 'Published Asc',
  'filter-bar.published-desc': 'Published Desc',
  'filter-bar.all': 'All',
  'filter-bar.faves': 'Faves',
  'filter-bar.wishlist': 'Wishlist',
  'filter-bar.unread': 'Unread',
  'filter-bar.show': 'Show: ',
  'filter-bar.sort': 'Sort: ',
  //
  'search-results-dialog.title': 'Search Results',
  'search-results-dialog.body':
      'Multiple results have been found!  Please select the correct book for your collection:',
  //
  'grid-resize-modal': <String, dynamic>{'title': 'Grid item size: '},
  //
  'color-picker.title': 'Choose Accent Color',
  'color-picker.submit-button': 'OK',
};
