final Map<String, String> frenchStrings = <String, String>{
  'app-title': 'Librarian',
  'login-button': 'Login',
  'register-button': 'Register',
  'cancel': 'Cancel',
  'search': 'Search',
  'yes': 'Yes',
  'no': 'No',
  'exit-confirmation-message': 'Do you want to exit?',
  'google-sign-in-button': 'Sign in with Google',
  'search-collection': 'Search collection ...',
  'languages-en': 'English',
  'languages-fr': 'French',
  'languages-es': 'Spanish',
  'error': 'Error',
  'submit': 'Submit',
  'ok': 'OK',
  'forgot-password': 'Forgot password',
  'send': 'Send',
  'save': 'Save',
  'delete': 'Delete',
  'confirm-delete': 'Confirm Delete',
  'delete-book-confirm-pt1': 'Are you sure you want to delete "',
  'delete-book-confirm-pt2': '"?  This cannot be undone.',
  'credits': '© 2023 Rob Vandelinder',
  //
  'login.email': 'Email',
  'login.password': 'Password',
  'login.sign-in': 'Sign In',
  'login.verify-email': 'Verify email address before signing in!',
  'login.error-initializing': 'Error initializing Firebase',
  'login.empty-email': 'Email cannot be empty!',
  'login.email-format': 'Email must be proper format!',
  'login.empty-password': 'Password cannot be empty!',
  'login.create-account': 'Sign Up',
  'login.forgot-password': 'Forgot Password?',
  'login.reset-pass-sent': 'Password reset email has been sent to @email',
  'login.email-error': 'Account with that email could not be found!',
  //
  'drawer.1-book-msg': '1 book in library',
  'drawer.no-books-msg': 'No books in library',
  'drawer.num-books-msg': '@numBooks books in library',
  'drawer.signed-in-as': 'Signed in as',
  'drawer.about-app': 'About app',
  'drawer.sign-out': 'Sign out',
  'drawer.settings.title': 'Settings',
  'drawer.settings.dark-mode': 'Dark Mode',
  'drawer.settings.light-mode': 'Light Mode',
  'drawer.clear-library': 'Clear Library',
  'drawer.confirm-clear':
      'Are you sure you want to delete your entire library?  ',
  'drawer.cannot-be-undone': 'This cannot be undone',
  'drawer.about-app-blurb':
      'Easily track books you\'ve read, books you want to purchase, and all your favorites in one simple location',
  //
  'parse-error.author': 'Unknown author',
  'parse-error.title': 'Unknown title',
  'parse-error.publisher': 'Unknown Publisher',
  //
  'manual-search-dialog.title': 'Keyword Search',
  'manual-search-dialog.body':
      'Search for new books using one or more keywords below',
  'manual-search-dialog.search-row-labels.keywords': 'Keywords',
  'manual-search-dialog.search-row-labels.title': 'Title',
  'manual-search-dialog.search-row-labels.author': 'Author',
  'manual-search-dialog.search-row-labels.publisher': 'Publisher',
  'manual-search-dialog.search-row-labels.isbn': 'ISBN',
  //
  'book-details-screen.page-count': '@pageCount pages',
  'book-details-screen.publisher': 'Published @publishYear by @publisher',
  'book-details-screen.empty-publishYear': 'Published by @publisher',
  'book-details-screen.empty-publisher': 'Published @publishYear',
  'book-details-screen.in-faves': 'In Faves',
  'book-details-screen.in-wishlist': 'In Wishlist',
  'book-details-screen.in-shopping-list': 'In Shopping List',
  'book-details-screen.have-read': 'Have Read',
  //
  'fancy-fab.barcode-search': 'Search by barcode',
  'fancy-fab.keyword-search': 'Search by keywords',
  'fancy-fab.add-book-manually': 'Add book manually',
  //
  'filter-bar.new': 'New',
  'filter-bar.old': 'Old',
  'filter-bar.author-asc': 'Author Asc',
  'filter-bar.author-desc': 'Author Desc',
  'filter-bar.title-asc': 'Title Asc',
  'filter-bar.title-desc': 'Title Desc',
  'filter-bar.published-asc': 'Published Asc',
  'filter-bar.published-desc': 'Published Desc',
  'filter-bar.all': 'All',
  'filter-bar.faves': 'Faves',
  'filter-bar.wishlist': 'Wishlist',
  'filter-bar.unread': 'Unread',
  'filter-bar.show': 'Show: ',
  'filter-bar.sort': 'Sort: ',
  //
  'search-results-dialog.title': 'Search Results',
  'search-results-dialog.body':
      'Multiple results have been found!  Please select the correct book for your collection:',
  'search-error.barcode': 'Try a different barcode.',
  //
  'grid-resize-modal.title': 'Grid item size: ',
  //
  'color-picker.title': 'Choose Accent Color',
  'color-picker.label': 'Accent Color: ',
  //
  'error-dialog.content': 'No results found!  @error',
  'send-reset-link':
      'Enter your email address to have a password reset link sent to your inbox.',
  //
  'new-book.title-error': 'Title cannot be empty',
  'new-book.title': 'Title',
  'new-book.author': 'Author',
  'new-book.publisher': 'Publisher',
  'new-book.publish-year': 'Publish Year',
  'new-book.page-count': 'Page Count',
  'new-book.description': 'Description',
  'new-book.rating': 'Rating',
  'new-book.is-mature': 'Mature content',
  'new-book.add-to-wishlist': 'Add to wishlist',
  'new-book.add-to-shopping-list': 'Add to shopping list',
  'new-book.have-read': 'Already read it',
  'new-book.add-to-faves': 'Add to favorites',
  'new-book.isbn': 'ISBN',
  'new-book.already-exists':
      'This book is already in your library!  Try a different book.',
};
